### ISSUE TITLE
Include sample snippet for the reason why the package was made

### ISSUE THREAD

**Issue by salhernandez** [ryanlaws/promise-registry#2]
The following is stated in the Readme:

> This can be particularly useful for asynchronous dependencies during e.g. initialization. Steps are named, and dependencies and dependents can be declared separately and loaded in the correct order as long as they share the registry.

It would be nice if a sample snippet was provided to solve this use case

**Comment by ryanlaws** [comment]
Agreed! That's a pretty murky description. This documentation needs some love!

**Comment by ryanlaws** [comment]
@salhernandez, how's #5 ?
